CREATE TABLE nessus_hosts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nessus_report_id INTEGER,
    name TEXT,
    os TEXT,
    mac TEXT,
    start TIMESTAMP,
    end TIMESTAMP,
    ip TEXT,
    fqdn TEXT,
    netbios TEXT,
    notes TEXT,
    risk_score INTEGER,
    user_id INTEGER,
    engagement_id INTEGER
);

CREATE TABLE nessus_host_properties (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    host_id INTEGER REFERENCES nessus_hosts(id),
    name TEXT,
    value TEXT,
    user_id INTEGER,
    engagement_id INTEGER
);

CREATE TABLE nessus_plugins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plugin_id INTEGER,
    plugin_name TEXT,
    family_name TEXT,
    description TEXT,
    plugin_version TEXT,
    plugin_publication_date TIMESTAMP,
    plugin_modification_date TIMESTAMP,
    vuln_publication_date TIMESTAMP,
    cvss_vector TEXT,
    cvss_base_score REAL,
    cvss_temporal_score TEXT,
    cvss_temporal_vector TEXT,
    exploitability_ease TEXT,
    exploit_framework_core TEXT,
    exploit_framework_metasploit TEXT,
    metasploit_name TEXT,
    exploit_framework_canvas TEXT,
    canvas_package TEXT,
    exploit_available TEXT,
    risk_factor TEXT,
    solution TEXT,
    synopsis TEXT,
    plugin_type TEXT,
    exploit_framework_exploithub TEXT,
    exploithub_sku TEXT,
    stig_severity TEXT,
    fname TEXT,
    always_run TEXT,
    script_version TEXT,
    d2_elliot_name TEXT,
    exploit_framework_d2_elliot TEXT,
    exploited_by_malware TEXT,
    rollup BOOLEAN,
    risk_score INTEGER,
    compliance TEXT,
    root_cause TEXT,
    agent TEXT,
    potential_vulnerability BOOLEAN,
    in_the_news BOOLEAN,
    exploited_by_nessus BOOLEAN,
    unsupported_by_vendor BOOLEAN,
    default_account BOOLEAN,
    user_id INTEGER,
    engagement_id INTEGER,
    policy_id INTEGER
);

CREATE TABLE nessus_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    host_id INTEGER REFERENCES nessus_hosts(id),
    plugin_id INTEGER REFERENCES nessus_plugins(id),
    attachment_id INTEGER,
    plugin_output TEXT,
    port INTEGER,
    svc_name TEXT,
    protocol TEXT,
    severity INTEGER,
    plugin_name TEXT,
    description TEXT,
    solution TEXT,
    risk_factor TEXT,
    cvss_base_score REAL,
    verified BOOLEAN,
    cm_compliance_info TEXT,
    cm_compliance_actual_value TEXT,
    cm_compliance_check_id TEXT,
    cm_compliance_policy_value TEXT,
    cm_compliance_audit_file TEXT,
    cm_compliance_check_name TEXT,
    cm_compliance_result TEXT,
    cm_compliance_output TEXT,
    cm_compliance_reference TEXT,
    cm_compliance_see_also TEXT,
    cm_compliance_solution TEXT,
    real_severity INTEGER,
    risk_score INTEGER,
    user_id INTEGER,
    engagement_id INTEGER
);

CREATE INDEX index_nessus_items_on_host_id ON nessus_items(host_id);
CREATE INDEX index_nessus_items_on_plugin_id ON nessus_items(plugin_id);
